"""Add model risk and lifecycle fields

Revision ID: 300bac7207ad
Revises: 85201bdfec2c
Create Date: 2026-08-11 02:38:51.118106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300bac7207ad'
down_revision: Union[str, Sequence[str], None] = '85201bdfec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('risk_tier', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('models', sa.Column('lifecycle_status', sa.String(length=30), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'lifecycle_status')
    op.drop_column('models', 'risk_tier')
    # ### end Alembic commands ###
